*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 06.12.2021 at 19:33:14
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZTSKY_V_ORDER...................................*
FORM GET_DATA_ZTSKY_V_ORDER.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSKY_D_ORDER WHERE
(VIM_WHERETAB) .
    CLEAR ZTSKY_V_ORDER .
ZTSKY_V_ORDER-MANDT =
ZTSKY_D_ORDER-MANDT .
ZTSKY_V_ORDER-ID_ORDER =
ZTSKY_D_ORDER-ID_ORDER .
ZTSKY_V_ORDER-ID_PIZZA =
ZTSKY_D_ORDER-ID_PIZZA .
ZTSKY_V_ORDER-ID_SIZE =
ZTSKY_D_ORDER-ID_SIZE .
    SELECT SINGLE * FROM ZTSKY_D_PIZZA WHERE
ID_PIZZA = ZTSKY_D_ORDER-ID_PIZZA .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZTSKY_D_PIZZA_T WHERE
ID_PIZZA = ZTSKY_D_PIZZA-ID_PIZZA AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZTSKY_V_ORDER-PIZZA_NAME =
ZTSKY_D_PIZZA_T-PIZZA_NAME .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM ZTSKY_D_SIZE WHERE
ID_SIZE = ZTSKY_D_ORDER-ID_SIZE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZTSKY_D_SIZE_T WHERE
ID_SIZE = ZTSKY_D_SIZE-ID_SIZE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZTSKY_V_ORDER-SIZE_NAME =
ZTSKY_D_SIZE_T-SIZE_NAME .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZTSKY_V_ORDER.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZTSKY_V_ORDER .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZTSKY_V_ORDER.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZTSKY_V_ORDER-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSKY_D_ORDER WHERE
  ID_ORDER = ZTSKY_V_ORDER-ID_ORDER AND
  ID_PIZZA = ZTSKY_V_ORDER-ID_PIZZA AND
  ID_SIZE = ZTSKY_V_ORDER-ID_SIZE .
    IF SY-SUBRC = 0.
    DELETE ZTSKY_D_ORDER .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSKY_D_ORDER WHERE
  ID_ORDER = ZTSKY_V_ORDER-ID_ORDER AND
  ID_PIZZA = ZTSKY_V_ORDER-ID_PIZZA AND
  ID_SIZE = ZTSKY_V_ORDER-ID_SIZE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSKY_D_ORDER.
    ENDIF.
ZTSKY_D_ORDER-MANDT =
ZTSKY_V_ORDER-MANDT .
ZTSKY_D_ORDER-ID_ORDER =
ZTSKY_V_ORDER-ID_ORDER .
ZTSKY_D_ORDER-ID_PIZZA =
ZTSKY_V_ORDER-ID_PIZZA .
ZTSKY_D_ORDER-ID_SIZE =
ZTSKY_V_ORDER-ID_SIZE .
    IF SY-SUBRC = 0.
    UPDATE ZTSKY_D_ORDER .
    ELSE.
    INSERT ZTSKY_D_ORDER .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZTSKY_V_ORDER-UPD_FLAG,
STATUS_ZTSKY_V_ORDER-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZTSKY_V_ORDER.
  SELECT SINGLE * FROM ZTSKY_D_ORDER WHERE
ID_ORDER = ZTSKY_V_ORDER-ID_ORDER AND
ID_PIZZA = ZTSKY_V_ORDER-ID_PIZZA AND
ID_SIZE = ZTSKY_V_ORDER-ID_SIZE .
ZTSKY_V_ORDER-MANDT =
ZTSKY_D_ORDER-MANDT .
ZTSKY_V_ORDER-ID_ORDER =
ZTSKY_D_ORDER-ID_ORDER .
ZTSKY_V_ORDER-ID_PIZZA =
ZTSKY_D_ORDER-ID_PIZZA .
ZTSKY_V_ORDER-ID_SIZE =
ZTSKY_D_ORDER-ID_SIZE .
    SELECT SINGLE * FROM ZTSKY_D_PIZZA WHERE
ID_PIZZA = ZTSKY_D_ORDER-ID_PIZZA .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZTSKY_D_PIZZA_T WHERE
ID_PIZZA = ZTSKY_D_PIZZA-ID_PIZZA AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZTSKY_V_ORDER-PIZZA_NAME =
ZTSKY_D_PIZZA_T-PIZZA_NAME .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZTSKY_V_ORDER-PIZZA_NAME .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZTSKY_V_ORDER-PIZZA_NAME .
    ENDIF.
    SELECT SINGLE * FROM ZTSKY_D_SIZE WHERE
ID_SIZE = ZTSKY_D_ORDER-ID_SIZE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZTSKY_D_SIZE_T WHERE
ID_SIZE = ZTSKY_D_SIZE-ID_SIZE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZTSKY_V_ORDER-SIZE_NAME =
ZTSKY_D_SIZE_T-SIZE_NAME .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZTSKY_V_ORDER-SIZE_NAME .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZTSKY_V_ORDER-SIZE_NAME .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZTSKY_V_ORDER USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZTSKY_V_ORDER-ID_ORDER TO
ZTSKY_D_ORDER-ID_ORDER .
MOVE ZTSKY_V_ORDER-ID_PIZZA TO
ZTSKY_D_ORDER-ID_PIZZA .
MOVE ZTSKY_V_ORDER-ID_SIZE TO
ZTSKY_D_ORDER-ID_SIZE .
MOVE ZTSKY_V_ORDER-MANDT TO
ZTSKY_D_ORDER-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSKY_D_ORDER'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSKY_D_ORDER TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSKY_D_ORDER'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZTSKY_V_ORDER USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZTSKY_D_ORDER-MANDT =
ZTSKY_V_ORDER-MANDT .
ZTSKY_D_ORDER-ID_ORDER =
ZTSKY_V_ORDER-ID_ORDER .
ZTSKY_D_ORDER-ID_PIZZA =
ZTSKY_V_ORDER-ID_PIZZA .
ZTSKY_D_ORDER-ID_SIZE =
ZTSKY_V_ORDER-ID_SIZE .
    SELECT SINGLE * FROM ZTSKY_D_PIZZA WHERE
ID_PIZZA = ZTSKY_D_ORDER-ID_PIZZA .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZTSKY_D_PIZZA_T WHERE
ID_PIZZA = ZTSKY_D_PIZZA-ID_PIZZA AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZTSKY_V_ORDER-PIZZA_NAME =
ZTSKY_D_PIZZA_T-PIZZA_NAME .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZTSKY_V_ORDER-PIZZA_NAME .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZTSKY_V_ORDER-PIZZA_NAME .
    ENDIF.
    SELECT SINGLE * FROM ZTSKY_D_SIZE WHERE
ID_SIZE = ZTSKY_D_ORDER-ID_SIZE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZTSKY_D_SIZE_T WHERE
ID_SIZE = ZTSKY_D_SIZE-ID_SIZE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZTSKY_V_ORDER-SIZE_NAME =
ZTSKY_D_SIZE_T-SIZE_NAME .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZTSKY_V_ORDER-SIZE_NAME .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZTSKY_V_ORDER-SIZE_NAME .
    ENDIF.
ENDFORM.
